// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: dynamic_filter.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SessionStatus int32

const (
	SessionStatus_SESSION_STATUS_UNSPECIFIED SessionStatus = 0
	SessionStatus_SESSION_STATUS_ACTIVE      SessionStatus = 1
	SessionStatus_SESSION_STATUS_COLLECTING  SessionStatus = 2
	SessionStatus_SESSION_STATUS_READY       SessionStatus = 3
	SessionStatus_SESSION_STATUS_COMPLETED   SessionStatus = 4
	SessionStatus_SESSION_STATUS_EXPIRED     SessionStatus = 5
	SessionStatus_SESSION_STATUS_ERROR       SessionStatus = 6
)

// Enum value maps for SessionStatus.
var (
	SessionStatus_name = map[int32]string{
		0: "SESSION_STATUS_UNSPECIFIED",
		1: "SESSION_STATUS_ACTIVE",
		2: "SESSION_STATUS_COLLECTING",
		3: "SESSION_STATUS_READY",
		4: "SESSION_STATUS_COMPLETED",
		5: "SESSION_STATUS_EXPIRED",
		6: "SESSION_STATUS_ERROR",
	}
	SessionStatus_value = map[string]int32{
		"SESSION_STATUS_UNSPECIFIED": 0,
		"SESSION_STATUS_ACTIVE":      1,
		"SESSION_STATUS_COLLECTING":  2,
		"SESSION_STATUS_READY":       3,
		"SESSION_STATUS_COMPLETED":   4,
		"SESSION_STATUS_EXPIRED":     5,
		"SESSION_STATUS_ERROR":       6,
	}
)

func (x SessionStatus) Enum() *SessionStatus {
	p := new(SessionStatus)
	*p = x
	return p
}

func (x SessionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_dynamic_filter_proto_enumTypes[0].Descriptor()
}

func (SessionStatus) Type() protoreflect.EnumType {
	return &file_dynamic_filter_proto_enumTypes[0]
}

func (x SessionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionStatus.Descriptor instead.
func (SessionStatus) EnumDescriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{0}
}

type FilterType int32

const (
	FilterType_FILTER_TYPE_UNSPECIFIED FilterType = 0
	FilterType_FILTER_TYPE_IN          FilterType = 1 // IN предикат
	FilterType_FILTER_TYPE_BETWEEN     FilterType = 2 // BETWEEN предикаты (OR)
)

// Enum value maps for FilterType.
var (
	FilterType_name = map[int32]string{
		0: "FILTER_TYPE_UNSPECIFIED",
		1: "FILTER_TYPE_IN",
		2: "FILTER_TYPE_BETWEEN",
	}
	FilterType_value = map[string]int32{
		"FILTER_TYPE_UNSPECIFIED": 0,
		"FILTER_TYPE_IN":          1,
		"FILTER_TYPE_BETWEEN":     2,
	}
)

func (x FilterType) Enum() *FilterType {
	p := new(FilterType)
	*p = x
	return p
}

func (x FilterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterType) Descriptor() protoreflect.EnumDescriptor {
	return file_dynamic_filter_proto_enumTypes[1].Descriptor()
}

func (FilterType) Type() protoreflect.EnumType {
	return &file_dynamic_filter_proto_enumTypes[1]
}

func (x FilterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterType.Descriptor instead.
func (FilterType) EnumDescriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{1}
}

type StartQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`                    // Уникальный ID запроса
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`              // Уникальный ID сегмента/сессии
	Mappings      []*FieldMapping        `protobuf:"bytes,3,rep,name=mappings,proto3" json:"mappings,omitempty"`                                 // Маппинг полей source->target
	TotalSegments int32                  `protobuf:"varint,4,opt,name=total_segments,json=totalSegments,proto3" json:"total_segments,omitempty"` // Общее количество сегментов в запросе
	TimeoutMs     int64                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`             // Таймаут сессии в миллисекундах
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartQueryRequest) Reset() {
	*x = StartQueryRequest{}
	mi := &file_dynamic_filter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartQueryRequest) ProtoMessage() {}

func (x *StartQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartQueryRequest.ProtoReflect.Descriptor instead.
func (*StartQueryRequest) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{0}
}

func (x *StartQueryRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *StartQueryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StartQueryRequest) GetMappings() []*FieldMapping {
	if x != nil {
		return x.Mappings
	}
	return nil
}

func (x *StartQueryRequest) GetTotalSegments() int32 {
	if x != nil {
		return x.TotalSegments
	}
	return 0
}

func (x *StartQueryRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type StartQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartQueryResponse) Reset() {
	*x = StartQueryResponse{}
	mi := &file_dynamic_filter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartQueryResponse) ProtoMessage() {}

func (x *StartQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartQueryResponse.ProtoReflect.Descriptor instead.
func (*StartQueryResponse) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{1}
}

func (x *StartQueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartQueryResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StopQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopQueryRequest) Reset() {
	*x = StopQueryRequest{}
	mi := &file_dynamic_filter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopQueryRequest) ProtoMessage() {}

func (x *StopQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopQueryRequest.ProtoReflect.Descriptor instead.
func (*StopQueryRequest) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{2}
}

func (x *StopQueryRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *StopQueryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StopQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopQueryResponse) Reset() {
	*x = StopQueryResponse{}
	mi := &file_dynamic_filter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopQueryResponse) ProtoMessage() {}

func (x *StopQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopQueryResponse.ProtoReflect.Descriptor instead.
func (*StopQueryResponse) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{3}
}

func (x *StopQueryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopQueryResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type QueryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryStatusRequest) Reset() {
	*x = QueryStatusRequest{}
	mi := &file_dynamic_filter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStatusRequest) ProtoMessage() {}

func (x *QueryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStatusRequest.ProtoReflect.Descriptor instead.
func (*QueryStatusRequest) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{4}
}

func (x *QueryStatusRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryStatusRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type QueryStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	QueryId            string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	Status             SessionStatus          `protobuf:"varint,2,opt,name=status,proto3,enum=dynamicfilter.SessionStatus" json:"status,omitempty"`
	RegisteredSegments int32                  `protobuf:"varint,3,opt,name=registered_segments,json=registeredSegments,proto3" json:"registered_segments,omitempty"`
	CompletedSources   int32                  `protobuf:"varint,4,opt,name=completed_sources,json=completedSources,proto3" json:"completed_sources,omitempty"`
	ReadyTargets       int32                  `protobuf:"varint,5,opt,name=ready_targets,json=readyTargets,proto3" json:"ready_targets,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QueryStatusResponse) Reset() {
	*x = QueryStatusResponse{}
	mi := &file_dynamic_filter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStatusResponse) ProtoMessage() {}

func (x *QueryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryStatusResponse.ProtoReflect.Descriptor instead.
func (*QueryStatusResponse) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{5}
}

func (x *QueryStatusResponse) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *QueryStatusResponse) GetStatus() SessionStatus {
	if x != nil {
		return x.Status
	}
	return SessionStatus_SESSION_STATUS_UNSPECIFIED
}

func (x *QueryStatusResponse) GetRegisteredSegments() int32 {
	if x != nil {
		return x.RegisteredSegments
	}
	return 0
}

func (x *QueryStatusResponse) GetCompletedSources() int32 {
	if x != nil {
		return x.CompletedSources
	}
	return 0
}

func (x *QueryStatusResponse) GetReadyTargets() int32 {
	if x != nil {
		return x.ReadyTargets
	}
	return 0
}

type FieldMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetAlias   string                 `protobuf:"bytes,1,opt,name=target_alias,json=targetAlias,proto3" json:"target_alias,omitempty"`          // Алиас target таблицы
	TargetField   string                 `protobuf:"bytes,2,opt,name=target_field,json=targetField,proto3" json:"target_field,omitempty"`          // Имя поля target таблицы
	SourceAlias   string                 `protobuf:"bytes,3,opt,name=source_alias,json=sourceAlias,proto3" json:"source_alias,omitempty"`          // Алиас source таблицы
	SourceField   string                 `protobuf:"bytes,4,opt,name=source_field,json=sourceField,proto3" json:"source_field,omitempty"`          // Имя поля source таблицы
	SourceFieldId int32                  `protobuf:"varint,5,opt,name=source_field_id,json=sourceFieldId,proto3" json:"source_field_id,omitempty"` // Iceberg field ID source
	TargetFieldId int32                  `protobuf:"varint,6,opt,name=target_field_id,json=targetFieldId,proto3" json:"target_field_id,omitempty"` // Iceberg field ID target
	FieldType     string                 `protobuf:"bytes,7,opt,name=field_type,json=fieldType,proto3" json:"field_type,omitempty"`                // Iceberg type name (int32, string, etc.)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldMapping) Reset() {
	*x = FieldMapping{}
	mi := &file_dynamic_filter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldMapping) ProtoMessage() {}

func (x *FieldMapping) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldMapping.ProtoReflect.Descriptor instead.
func (*FieldMapping) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{6}
}

func (x *FieldMapping) GetTargetAlias() string {
	if x != nil {
		return x.TargetAlias
	}
	return ""
}

func (x *FieldMapping) GetTargetField() string {
	if x != nil {
		return x.TargetField
	}
	return ""
}

func (x *FieldMapping) GetSourceAlias() string {
	if x != nil {
		return x.SourceAlias
	}
	return ""
}

func (x *FieldMapping) GetSourceField() string {
	if x != nil {
		return x.SourceField
	}
	return ""
}

func (x *FieldMapping) GetSourceFieldId() int32 {
	if x != nil {
		return x.SourceFieldId
	}
	return 0
}

func (x *FieldMapping) GetTargetFieldId() int32 {
	if x != nil {
		return x.TargetFieldId
	}
	return 0
}

func (x *FieldMapping) GetFieldType() string {
	if x != nil {
		return x.FieldType
	}
	return ""
}

type CollectValueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SourceAlias   string                 `protobuf:"bytes,3,opt,name=source_alias,json=sourceAlias,proto3" json:"source_alias,omitempty"`
	FieldName     string                 `protobuf:"bytes,4,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`        // Имя поля (вместо field_id)
	Values        []*Literal             `protobuf:"bytes,5,rep,name=values,proto3" json:"values,omitempty"`                               // Пакет значений
	IsFinal       bool                   `protobuf:"varint,6,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`             // true если это последний пакет
	SequenceNum   int64                  `protobuf:"varint,7,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"` // Номер пакета для упорядочивания
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CollectValueRequest) Reset() {
	*x = CollectValueRequest{}
	mi := &file_dynamic_filter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectValueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectValueRequest) ProtoMessage() {}

func (x *CollectValueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectValueRequest.ProtoReflect.Descriptor instead.
func (*CollectValueRequest) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{7}
}

func (x *CollectValueRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *CollectValueRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CollectValueRequest) GetSourceAlias() string {
	if x != nil {
		return x.SourceAlias
	}
	return ""
}

func (x *CollectValueRequest) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *CollectValueRequest) GetValues() []*Literal {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *CollectValueRequest) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *CollectValueRequest) GetSequenceNum() int64 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

type CollectValueResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Success             bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage        string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TotalValuesReceived int64                  `protobuf:"varint,3,opt,name=total_values_received,json=totalValuesReceived,proto3" json:"total_values_received,omitempty"` // Общее количество полученных значений
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CollectValueResponse) Reset() {
	*x = CollectValueResponse{}
	mi := &file_dynamic_filter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CollectValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CollectValueResponse) ProtoMessage() {}

func (x *CollectValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CollectValueResponse.ProtoReflect.Descriptor instead.
func (*CollectValueResponse) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{8}
}

func (x *CollectValueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CollectValueResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *CollectValueResponse) GetTotalValuesReceived() int64 {
	if x != nil {
		return x.TotalValuesReceived
	}
	return 0
}

type SignalSourceCompleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SourceAlias   string                 `protobuf:"bytes,3,opt,name=source_alias,json=sourceAlias,proto3" json:"source_alias,omitempty"`
	FieldName     string                 `protobuf:"bytes,4,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"` // Имя поля (вместо field_id)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalSourceCompleteRequest) Reset() {
	*x = SignalSourceCompleteRequest{}
	mi := &file_dynamic_filter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalSourceCompleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalSourceCompleteRequest) ProtoMessage() {}

func (x *SignalSourceCompleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalSourceCompleteRequest.ProtoReflect.Descriptor instead.
func (*SignalSourceCompleteRequest) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{9}
}

func (x *SignalSourceCompleteRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *SignalSourceCompleteRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SignalSourceCompleteRequest) GetSourceAlias() string {
	if x != nil {
		return x.SourceAlias
	}
	return ""
}

func (x *SignalSourceCompleteRequest) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

type SignalSourceCompleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	FilterReady   bool                   `protobuf:"varint,3,opt,name=filter_ready,json=filterReady,proto3" json:"filter_ready,omitempty"` // true если фильтр готов для target
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalSourceCompleteResponse) Reset() {
	*x = SignalSourceCompleteResponse{}
	mi := &file_dynamic_filter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalSourceCompleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalSourceCompleteResponse) ProtoMessage() {}

func (x *SignalSourceCompleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalSourceCompleteResponse.ProtoReflect.Descriptor instead.
func (*SignalSourceCompleteResponse) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{10}
}

func (x *SignalSourceCompleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SignalSourceCompleteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SignalSourceCompleteResponse) GetFilterReady() bool {
	if x != nil {
		return x.FilterReady
	}
	return false
}

type GetFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TargetAlias   string                 `protobuf:"bytes,3,opt,name=target_alias,json=targetAlias,proto3" json:"target_alias,omitempty"`
	FieldName     string                 `protobuf:"bytes,4,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"` // Имя поля (вместо field_id)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilterRequest) Reset() {
	*x = GetFilterRequest{}
	mi := &file_dynamic_filter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilterRequest) ProtoMessage() {}

func (x *GetFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilterRequest.ProtoReflect.Descriptor instead.
func (*GetFilterRequest) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{11}
}

func (x *GetFilterRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *GetFilterRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GetFilterRequest) GetTargetAlias() string {
	if x != nil {
		return x.TargetAlias
	}
	return ""
}

func (x *GetFilterRequest) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

type GetFilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsReady       bool                   `protobuf:"varint,1,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"` // Готов ли фильтр
	Filter        *DynamicFilter         `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`                   // Фильтр (если готов)
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilterResponse) Reset() {
	*x = GetFilterResponse{}
	mi := &file_dynamic_filter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilterResponse) ProtoMessage() {}

func (x *GetFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilterResponse.ProtoReflect.Descriptor instead.
func (*GetFilterResponse) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{12}
}

func (x *GetFilterResponse) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *GetFilterResponse) GetFilter() *DynamicFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *GetFilterResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type WaitForFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TargetAlias   string                 `protobuf:"bytes,3,opt,name=target_alias,json=targetAlias,proto3" json:"target_alias,omitempty"`
	FieldName     string                 `protobuf:"bytes,4,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`  // Имя поля (вместо field_id)
	TimeoutMs     int64                  `protobuf:"varint,5,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"` // Максимальное время ожидания
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForFilterRequest) Reset() {
	*x = WaitForFilterRequest{}
	mi := &file_dynamic_filter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForFilterRequest) ProtoMessage() {}

func (x *WaitForFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForFilterRequest.ProtoReflect.Descriptor instead.
func (*WaitForFilterRequest) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{13}
}

func (x *WaitForFilterRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *WaitForFilterRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WaitForFilterRequest) GetTargetAlias() string {
	if x != nil {
		return x.TargetAlias
	}
	return ""
}

func (x *WaitForFilterRequest) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *WaitForFilterRequest) GetTimeoutMs() int64 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type WaitForFilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsReady       bool                   `protobuf:"varint,1,opt,name=is_ready,json=isReady,proto3" json:"is_ready,omitempty"`
	Filter        *DynamicFilter         `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TimedOut      bool                   `protobuf:"varint,4,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"` // true если истёк таймаут
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitForFilterResponse) Reset() {
	*x = WaitForFilterResponse{}
	mi := &file_dynamic_filter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitForFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitForFilterResponse) ProtoMessage() {}

func (x *WaitForFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitForFilterResponse.ProtoReflect.Descriptor instead.
func (*WaitForFilterResponse) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{14}
}

func (x *WaitForFilterResponse) GetIsReady() bool {
	if x != nil {
		return x.IsReady
	}
	return false
}

func (x *WaitForFilterResponse) GetFilter() *DynamicFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *WaitForFilterResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *WaitForFilterResponse) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

type DynamicFilter struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FieldName        string                 `protobuf:"bytes,1,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`                                   // Имя поля target
	FieldType        string                 `protobuf:"bytes,2,opt,name=field_type,json=fieldType,proto3" json:"field_type,omitempty"`                                   // Iceberg type name
	FilterType       FilterType             `protobuf:"varint,3,opt,name=filter_type,json=filterType,proto3,enum=dynamicfilter.FilterType" json:"filter_type,omitempty"` // Тип фильтра (IN или BETWEEN)
	InValues         []*Literal             `protobuf:"bytes,4,rep,name=in_values,json=inValues,proto3" json:"in_values,omitempty"`                                      // Значения для IN фильтра
	Ranges           []*ValueRange          `protobuf:"bytes,5,rep,name=ranges,proto3" json:"ranges,omitempty"`                                                          // Диапазоны для BETWEEN фильтра
	TotalValues      int64                  `protobuf:"varint,6,opt,name=total_values,json=totalValues,proto3" json:"total_values,omitempty"`                            // Общее количество собранных значений
	BuildTimestampMs int64                  `protobuf:"varint,7,opt,name=build_timestamp_ms,json=buildTimestampMs,proto3" json:"build_timestamp_ms,omitempty"`           // Время построения фильтра
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DynamicFilter) Reset() {
	*x = DynamicFilter{}
	mi := &file_dynamic_filter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamicFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamicFilter) ProtoMessage() {}

func (x *DynamicFilter) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamicFilter.ProtoReflect.Descriptor instead.
func (*DynamicFilter) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{15}
}

func (x *DynamicFilter) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *DynamicFilter) GetFieldType() string {
	if x != nil {
		return x.FieldType
	}
	return ""
}

func (x *DynamicFilter) GetFilterType() FilterType {
	if x != nil {
		return x.FilterType
	}
	return FilterType_FILTER_TYPE_UNSPECIFIED
}

func (x *DynamicFilter) GetInValues() []*Literal {
	if x != nil {
		return x.InValues
	}
	return nil
}

func (x *DynamicFilter) GetRanges() []*ValueRange {
	if x != nil {
		return x.Ranges
	}
	return nil
}

func (x *DynamicFilter) GetTotalValues() int64 {
	if x != nil {
		return x.TotalValues
	}
	return 0
}

func (x *DynamicFilter) GetBuildTimestampMs() int64 {
	if x != nil {
		return x.BuildTimestampMs
	}
	return 0
}

type ValueRange struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Lower          *Literal               `protobuf:"bytes,1,opt,name=lower,proto3" json:"lower,omitempty"`                                          // Нижняя граница
	Upper          *Literal               `protobuf:"bytes,2,opt,name=upper,proto3" json:"upper,omitempty"`                                          // Верхняя граница
	LowerInclusive bool                   `protobuf:"varint,3,opt,name=lower_inclusive,json=lowerInclusive,proto3" json:"lower_inclusive,omitempty"` // Нижняя граница включительна
	UpperInclusive bool                   `protobuf:"varint,4,opt,name=upper_inclusive,json=upperInclusive,proto3" json:"upper_inclusive,omitempty"` // Верхняя граница включительна
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValueRange) Reset() {
	*x = ValueRange{}
	mi := &file_dynamic_filter_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueRange) ProtoMessage() {}

func (x *ValueRange) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueRange.ProtoReflect.Descriptor instead.
func (*ValueRange) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{16}
}

func (x *ValueRange) GetLower() *Literal {
	if x != nil {
		return x.Lower
	}
	return nil
}

func (x *ValueRange) GetUpper() *Literal {
	if x != nil {
		return x.Upper
	}
	return nil
}

func (x *ValueRange) GetLowerInclusive() bool {
	if x != nil {
		return x.LowerInclusive
	}
	return false
}

func (x *ValueRange) GetUpperInclusive() bool {
	if x != nil {
		return x.UpperInclusive
	}
	return false
}

type Literal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Literal_BoolValue
	//	*Literal_Int32Value
	//	*Literal_Int64Value
	//	*Literal_Float32Value
	//	*Literal_Float64Value
	//	*Literal_StringValue
	//	*Literal_BytesValue
	//	*Literal_DateValue
	//	*Literal_TimeValue
	//	*Literal_TimestampValue
	//	*Literal_DecimalValue
	//	*Literal_UuidValue
	//	*Literal_FixedValue
	Value         isLiteral_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Literal) Reset() {
	*x = Literal{}
	mi := &file_dynamic_filter_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Literal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Literal) ProtoMessage() {}

func (x *Literal) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Literal.ProtoReflect.Descriptor instead.
func (*Literal) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{17}
}

func (x *Literal) GetValue() isLiteral_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Literal) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Literal_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Literal) GetInt32Value() int32 {
	if x != nil {
		if x, ok := x.Value.(*Literal_Int32Value); ok {
			return x.Int32Value
		}
	}
	return 0
}

func (x *Literal) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Value.(*Literal_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *Literal) GetFloat32Value() float32 {
	if x != nil {
		if x, ok := x.Value.(*Literal_Float32Value); ok {
			return x.Float32Value
		}
	}
	return 0
}

func (x *Literal) GetFloat64Value() float64 {
	if x != nil {
		if x, ok := x.Value.(*Literal_Float64Value); ok {
			return x.Float64Value
		}
	}
	return 0
}

func (x *Literal) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Literal_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Literal) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*Literal_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *Literal) GetDateValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Literal_DateValue); ok {
			return x.DateValue
		}
	}
	return 0
}

func (x *Literal) GetTimeValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Literal_TimeValue); ok {
			return x.TimeValue
		}
	}
	return 0
}

func (x *Literal) GetTimestampValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*Literal_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return 0
}

func (x *Literal) GetDecimalValue() string {
	if x != nil {
		if x, ok := x.Value.(*Literal_DecimalValue); ok {
			return x.DecimalValue
		}
	}
	return ""
}

func (x *Literal) GetUuidValue() string {
	if x != nil {
		if x, ok := x.Value.(*Literal_UuidValue); ok {
			return x.UuidValue
		}
	}
	return ""
}

func (x *Literal) GetFixedValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*Literal_FixedValue); ok {
			return x.FixedValue
		}
	}
	return nil
}

type isLiteral_Value interface {
	isLiteral_Value()
}

type Literal_BoolValue struct {
	// Примитивные типы
	BoolValue bool `protobuf:"varint,1,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Literal_Int32Value struct {
	Int32Value int32 `protobuf:"varint,2,opt,name=int32_value,json=int32Value,proto3,oneof"`
}

type Literal_Int64Value struct {
	Int64Value int64 `protobuf:"varint,3,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Literal_Float32Value struct {
	Float32Value float32 `protobuf:"fixed32,4,opt,name=float32_value,json=float32Value,proto3,oneof"`
}

type Literal_Float64Value struct {
	Float64Value float64 `protobuf:"fixed64,5,opt,name=float64_value,json=float64Value,proto3,oneof"`
}

type Literal_StringValue struct {
	// Строковые и бинарные
	StringValue string `protobuf:"bytes,6,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Literal_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,7,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type Literal_DateValue struct {
	// Временные типы (хранятся как int64)
	DateValue int64 `protobuf:"varint,8,opt,name=date_value,json=dateValue,proto3,oneof"` // Дней с epoch
}

type Literal_TimeValue struct {
	TimeValue int64 `protobuf:"varint,9,opt,name=time_value,json=timeValue,proto3,oneof"` // Микросекунды с начала дня
}

type Literal_TimestampValue struct {
	TimestampValue int64 `protobuf:"varint,10,opt,name=timestamp_value,json=timestampValue,proto3,oneof"` // Микросекунд с epoch
}

type Literal_DecimalValue struct {
	// Decimal (строковое представление)
	DecimalValue string `protobuf:"bytes,11,opt,name=decimal_value,json=decimalValue,proto3,oneof"`
}

type Literal_UuidValue struct {
	// UUID
	UuidValue string `protobuf:"bytes,12,opt,name=uuid_value,json=uuidValue,proto3,oneof"`
}

type Literal_FixedValue struct {
	// Fixed (байтовый массив с длиной)
	FixedValue []byte `protobuf:"bytes,13,opt,name=fixed_value,json=fixedValue,proto3,oneof"`
}

func (*Literal_BoolValue) isLiteral_Value() {}

func (*Literal_Int32Value) isLiteral_Value() {}

func (*Literal_Int64Value) isLiteral_Value() {}

func (*Literal_Float32Value) isLiteral_Value() {}

func (*Literal_Float64Value) isLiteral_Value() {}

func (*Literal_StringValue) isLiteral_Value() {}

func (*Literal_BytesValue) isLiteral_Value() {}

func (*Literal_DateValue) isLiteral_Value() {}

func (*Literal_TimeValue) isLiteral_Value() {}

func (*Literal_TimestampValue) isLiteral_Value() {}

func (*Literal_DecimalValue) isLiteral_Value() {}

func (*Literal_UuidValue) isLiteral_Value() {}

func (*Literal_FixedValue) isLiteral_Value() {}

type RegisterSegmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SegmentHost   string                 `protobuf:"bytes,3,opt,name=segment_host,json=segmentHost,proto3" json:"segment_host,omitempty"`       // Хост сегмента
	SegmentPort   int32                  `protobuf:"varint,4,opt,name=segment_port,json=segmentPort,proto3" json:"segment_port,omitempty"`      // Порт сегмента
	SourceAliases []string               `protobuf:"bytes,5,rep,name=source_aliases,json=sourceAliases,proto3" json:"source_aliases,omitempty"` // Алиасы source таблиц на этом сегменте
	TargetAliases []string               `protobuf:"bytes,6,rep,name=target_aliases,json=targetAliases,proto3" json:"target_aliases,omitempty"` // Алиасы target таблиц на этом сегменте
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterSegmentRequest) Reset() {
	*x = RegisterSegmentRequest{}
	mi := &file_dynamic_filter_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSegmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSegmentRequest) ProtoMessage() {}

func (x *RegisterSegmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSegmentRequest.ProtoReflect.Descriptor instead.
func (*RegisterSegmentRequest) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{18}
}

func (x *RegisterSegmentRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *RegisterSegmentRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RegisterSegmentRequest) GetSegmentHost() string {
	if x != nil {
		return x.SegmentHost
	}
	return ""
}

func (x *RegisterSegmentRequest) GetSegmentPort() int32 {
	if x != nil {
		return x.SegmentPort
	}
	return 0
}

func (x *RegisterSegmentRequest) GetSourceAliases() []string {
	if x != nil {
		return x.SourceAliases
	}
	return nil
}

func (x *RegisterSegmentRequest) GetTargetAliases() []string {
	if x != nil {
		return x.TargetAliases
	}
	return nil
}

type RegisterSegmentResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TotalRegistered int32                  `protobuf:"varint,3,opt,name=total_registered,json=totalRegistered,proto3" json:"total_registered,omitempty"` // Общее количество зарегистрированных сегментов
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RegisterSegmentResponse) Reset() {
	*x = RegisterSegmentResponse{}
	mi := &file_dynamic_filter_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterSegmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSegmentResponse) ProtoMessage() {}

func (x *RegisterSegmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_filter_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSegmentResponse.ProtoReflect.Descriptor instead.
func (*RegisterSegmentResponse) Descriptor() ([]byte, []int) {
	return file_dynamic_filter_proto_rawDescGZIP(), []int{19}
}

func (x *RegisterSegmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterSegmentResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RegisterSegmentResponse) GetTotalRegistered() int32 {
	if x != nil {
		return x.TotalRegistered
	}
	return 0
}

var File_dynamic_filter_proto protoreflect.FileDescriptor

const file_dynamic_filter_proto_rawDesc = "" +
	"\n" +
	"\x14dynamic_filter.proto\x12\rdynamicfilter\"\xcc\x01\n" +
	"\x11StartQueryRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x127\n" +
	"\bmappings\x18\x03 \x03(\v2\x1b.dynamicfilter.FieldMappingR\bmappings\x12%\n" +
	"\x0etotal_segments\x18\x04 \x01(\x05R\rtotalSegments\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x03R\ttimeoutMs\"S\n" +
	"\x12StartQueryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"L\n" +
	"\x10StopQueryRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"R\n" +
	"\x11StopQueryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"N\n" +
	"\x12QueryStatusRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\xe9\x01\n" +
	"\x13QueryStatusResponse\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x124\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1c.dynamicfilter.SessionStatusR\x06status\x12/\n" +
	"\x13registered_segments\x18\x03 \x01(\x05R\x12registeredSegments\x12+\n" +
	"\x11completed_sources\x18\x04 \x01(\x05R\x10completedSources\x12#\n" +
	"\rready_targets\x18\x05 \x01(\x05R\freadyTargets\"\x89\x02\n" +
	"\fFieldMapping\x12!\n" +
	"\ftarget_alias\x18\x01 \x01(\tR\vtargetAlias\x12!\n" +
	"\ftarget_field\x18\x02 \x01(\tR\vtargetField\x12!\n" +
	"\fsource_alias\x18\x03 \x01(\tR\vsourceAlias\x12!\n" +
	"\fsource_field\x18\x04 \x01(\tR\vsourceField\x12&\n" +
	"\x0fsource_field_id\x18\x05 \x01(\x05R\rsourceFieldId\x12&\n" +
	"\x0ftarget_field_id\x18\x06 \x01(\x05R\rtargetFieldId\x12\x1d\n" +
	"\n" +
	"field_type\x18\a \x01(\tR\tfieldType\"\xff\x01\n" +
	"\x13CollectValueRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12!\n" +
	"\fsource_alias\x18\x03 \x01(\tR\vsourceAlias\x12\x1d\n" +
	"\n" +
	"field_name\x18\x04 \x01(\tR\tfieldName\x12.\n" +
	"\x06values\x18\x05 \x03(\v2\x16.dynamicfilter.LiteralR\x06values\x12\x19\n" +
	"\bis_final\x18\x06 \x01(\bR\aisFinal\x12!\n" +
	"\fsequence_num\x18\a \x01(\x03R\vsequenceNum\"\x89\x01\n" +
	"\x14CollectValueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x122\n" +
	"\x15total_values_received\x18\x03 \x01(\x03R\x13totalValuesReceived\"\x99\x01\n" +
	"\x1bSignalSourceCompleteRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12!\n" +
	"\fsource_alias\x18\x03 \x01(\tR\vsourceAlias\x12\x1d\n" +
	"\n" +
	"field_name\x18\x04 \x01(\tR\tfieldName\"\x80\x01\n" +
	"\x1cSignalSourceCompleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12!\n" +
	"\ffilter_ready\x18\x03 \x01(\bR\vfilterReady\"\x8e\x01\n" +
	"\x10GetFilterRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12!\n" +
	"\ftarget_alias\x18\x03 \x01(\tR\vtargetAlias\x12\x1d\n" +
	"\n" +
	"field_name\x18\x04 \x01(\tR\tfieldName\"\x89\x01\n" +
	"\x11GetFilterResponse\x12\x19\n" +
	"\bis_ready\x18\x01 \x01(\bR\aisReady\x124\n" +
	"\x06filter\x18\x02 \x01(\v2\x1c.dynamicfilter.DynamicFilterR\x06filter\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xb1\x01\n" +
	"\x14WaitForFilterRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12!\n" +
	"\ftarget_alias\x18\x03 \x01(\tR\vtargetAlias\x12\x1d\n" +
	"\n" +
	"field_name\x18\x04 \x01(\tR\tfieldName\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x05 \x01(\x03R\ttimeoutMs\"\xaa\x01\n" +
	"\x15WaitForFilterResponse\x12\x19\n" +
	"\bis_ready\x18\x01 \x01(\bR\aisReady\x124\n" +
	"\x06filter\x18\x02 \x01(\v2\x1c.dynamicfilter.DynamicFilterR\x06filter\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1b\n" +
	"\ttimed_out\x18\x04 \x01(\bR\btimedOut\"\xc2\x02\n" +
	"\rDynamicFilter\x12\x1d\n" +
	"\n" +
	"field_name\x18\x01 \x01(\tR\tfieldName\x12\x1d\n" +
	"\n" +
	"field_type\x18\x02 \x01(\tR\tfieldType\x12:\n" +
	"\vfilter_type\x18\x03 \x01(\x0e2\x19.dynamicfilter.FilterTypeR\n" +
	"filterType\x123\n" +
	"\tin_values\x18\x04 \x03(\v2\x16.dynamicfilter.LiteralR\binValues\x121\n" +
	"\x06ranges\x18\x05 \x03(\v2\x19.dynamicfilter.ValueRangeR\x06ranges\x12!\n" +
	"\ftotal_values\x18\x06 \x01(\x03R\vtotalValues\x12,\n" +
	"\x12build_timestamp_ms\x18\a \x01(\x03R\x10buildTimestampMs\"\xba\x01\n" +
	"\n" +
	"ValueRange\x12,\n" +
	"\x05lower\x18\x01 \x01(\v2\x16.dynamicfilter.LiteralR\x05lower\x12,\n" +
	"\x05upper\x18\x02 \x01(\v2\x16.dynamicfilter.LiteralR\x05upper\x12'\n" +
	"\x0flower_inclusive\x18\x03 \x01(\bR\x0elowerInclusive\x12'\n" +
	"\x0fupper_inclusive\x18\x04 \x01(\bR\x0eupperInclusive\"\xe7\x03\n" +
	"\aLiteral\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x01 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vint32_value\x18\x02 \x01(\x05H\x00R\n" +
	"int32Value\x12!\n" +
	"\vint64_value\x18\x03 \x01(\x03H\x00R\n" +
	"int64Value\x12%\n" +
	"\rfloat32_value\x18\x04 \x01(\x02H\x00R\ffloat32Value\x12%\n" +
	"\rfloat64_value\x18\x05 \x01(\x01H\x00R\ffloat64Value\x12#\n" +
	"\fstring_value\x18\x06 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vbytes_value\x18\a \x01(\fH\x00R\n" +
	"bytesValue\x12\x1f\n" +
	"\n" +
	"date_value\x18\b \x01(\x03H\x00R\tdateValue\x12\x1f\n" +
	"\n" +
	"time_value\x18\t \x01(\x03H\x00R\ttimeValue\x12)\n" +
	"\x0ftimestamp_value\x18\n" +
	" \x01(\x03H\x00R\x0etimestampValue\x12%\n" +
	"\rdecimal_value\x18\v \x01(\tH\x00R\fdecimalValue\x12\x1f\n" +
	"\n" +
	"uuid_value\x18\f \x01(\tH\x00R\tuuidValue\x12!\n" +
	"\vfixed_value\x18\r \x01(\fH\x00R\n" +
	"fixedValueB\a\n" +
	"\x05value\"\xe6\x01\n" +
	"\x16RegisterSegmentRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12!\n" +
	"\fsegment_host\x18\x03 \x01(\tR\vsegmentHost\x12!\n" +
	"\fsegment_port\x18\x04 \x01(\x05R\vsegmentPort\x12%\n" +
	"\x0esource_aliases\x18\x05 \x03(\tR\rsourceAliases\x12%\n" +
	"\x0etarget_aliases\x18\x06 \x03(\tR\rtargetAliases\"\x83\x01\n" +
	"\x17RegisterSegmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12)\n" +
	"\x10total_registered\x18\x03 \x01(\x05R\x0ftotalRegistered*\xd7\x01\n" +
	"\rSessionStatus\x12\x1e\n" +
	"\x1aSESSION_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15SESSION_STATUS_ACTIVE\x10\x01\x12\x1d\n" +
	"\x19SESSION_STATUS_COLLECTING\x10\x02\x12\x18\n" +
	"\x14SESSION_STATUS_READY\x10\x03\x12\x1c\n" +
	"\x18SESSION_STATUS_COMPLETED\x10\x04\x12\x1a\n" +
	"\x16SESSION_STATUS_EXPIRED\x10\x05\x12\x18\n" +
	"\x14SESSION_STATUS_ERROR\x10\x06*V\n" +
	"\n" +
	"FilterType\x12\x1b\n" +
	"\x17FILTER_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eFILTER_TYPE_IN\x10\x01\x12\x17\n" +
	"\x13FILTER_TYPE_BETWEEN\x10\x022\xea\x05\n" +
	"\x14DynamicFilterService\x12Q\n" +
	"\n" +
	"StartQuery\x12 .dynamicfilter.StartQueryRequest\x1a!.dynamicfilter.StartQueryResponse\x12N\n" +
	"\tStopQuery\x12\x1f.dynamicfilter.StopQueryRequest\x1a .dynamicfilter.StopQueryResponse\x12T\n" +
	"\vQueryStatus\x12!.dynamicfilter.QueryStatusRequest\x1a\".dynamicfilter.QueryStatusResponse\x12Z\n" +
	"\rCollectValues\x12\".dynamicfilter.CollectValueRequest\x1a#.dynamicfilter.CollectValueResponse(\x01\x12N\n" +
	"\tGetFilter\x12\x1f.dynamicfilter.GetFilterRequest\x1a .dynamicfilter.GetFilterResponse\x12Z\n" +
	"\rWaitForFilter\x12#.dynamicfilter.WaitForFilterRequest\x1a$.dynamicfilter.WaitForFilterResponse\x12`\n" +
	"\x0fRegisterSegment\x12%.dynamicfilter.RegisterSegmentRequest\x1a&.dynamicfilter.RegisterSegmentResponse\x12o\n" +
	"\x14SignalSourceComplete\x12*.dynamicfilter.SignalSourceCompleteRequest\x1a+.dynamicfilter.SignalSourceCompleteResponseB2Z0github.com/apache/iceberg-go/dynamicfilter/protob\x06proto3"

var (
	file_dynamic_filter_proto_rawDescOnce sync.Once
	file_dynamic_filter_proto_rawDescData []byte
)

func file_dynamic_filter_proto_rawDescGZIP() []byte {
	file_dynamic_filter_proto_rawDescOnce.Do(func() {
		file_dynamic_filter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dynamic_filter_proto_rawDesc), len(file_dynamic_filter_proto_rawDesc)))
	})
	return file_dynamic_filter_proto_rawDescData
}

var file_dynamic_filter_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_dynamic_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_dynamic_filter_proto_goTypes = []any{
	(SessionStatus)(0),                   // 0: dynamicfilter.SessionStatus
	(FilterType)(0),                      // 1: dynamicfilter.FilterType
	(*StartQueryRequest)(nil),            // 2: dynamicfilter.StartQueryRequest
	(*StartQueryResponse)(nil),           // 3: dynamicfilter.StartQueryResponse
	(*StopQueryRequest)(nil),             // 4: dynamicfilter.StopQueryRequest
	(*StopQueryResponse)(nil),            // 5: dynamicfilter.StopQueryResponse
	(*QueryStatusRequest)(nil),           // 6: dynamicfilter.QueryStatusRequest
	(*QueryStatusResponse)(nil),          // 7: dynamicfilter.QueryStatusResponse
	(*FieldMapping)(nil),                 // 8: dynamicfilter.FieldMapping
	(*CollectValueRequest)(nil),          // 9: dynamicfilter.CollectValueRequest
	(*CollectValueResponse)(nil),         // 10: dynamicfilter.CollectValueResponse
	(*SignalSourceCompleteRequest)(nil),  // 11: dynamicfilter.SignalSourceCompleteRequest
	(*SignalSourceCompleteResponse)(nil), // 12: dynamicfilter.SignalSourceCompleteResponse
	(*GetFilterRequest)(nil),             // 13: dynamicfilter.GetFilterRequest
	(*GetFilterResponse)(nil),            // 14: dynamicfilter.GetFilterResponse
	(*WaitForFilterRequest)(nil),         // 15: dynamicfilter.WaitForFilterRequest
	(*WaitForFilterResponse)(nil),        // 16: dynamicfilter.WaitForFilterResponse
	(*DynamicFilter)(nil),                // 17: dynamicfilter.DynamicFilter
	(*ValueRange)(nil),                   // 18: dynamicfilter.ValueRange
	(*Literal)(nil),                      // 19: dynamicfilter.Literal
	(*RegisterSegmentRequest)(nil),       // 20: dynamicfilter.RegisterSegmentRequest
	(*RegisterSegmentResponse)(nil),      // 21: dynamicfilter.RegisterSegmentResponse
}
var file_dynamic_filter_proto_depIdxs = []int32{
	8,  // 0: dynamicfilter.StartQueryRequest.mappings:type_name -> dynamicfilter.FieldMapping
	0,  // 1: dynamicfilter.QueryStatusResponse.status:type_name -> dynamicfilter.SessionStatus
	19, // 2: dynamicfilter.CollectValueRequest.values:type_name -> dynamicfilter.Literal
	17, // 3: dynamicfilter.GetFilterResponse.filter:type_name -> dynamicfilter.DynamicFilter
	17, // 4: dynamicfilter.WaitForFilterResponse.filter:type_name -> dynamicfilter.DynamicFilter
	1,  // 5: dynamicfilter.DynamicFilter.filter_type:type_name -> dynamicfilter.FilterType
	19, // 6: dynamicfilter.DynamicFilter.in_values:type_name -> dynamicfilter.Literal
	18, // 7: dynamicfilter.DynamicFilter.ranges:type_name -> dynamicfilter.ValueRange
	19, // 8: dynamicfilter.ValueRange.lower:type_name -> dynamicfilter.Literal
	19, // 9: dynamicfilter.ValueRange.upper:type_name -> dynamicfilter.Literal
	2,  // 10: dynamicfilter.DynamicFilterService.StartQuery:input_type -> dynamicfilter.StartQueryRequest
	4,  // 11: dynamicfilter.DynamicFilterService.StopQuery:input_type -> dynamicfilter.StopQueryRequest
	6,  // 12: dynamicfilter.DynamicFilterService.QueryStatus:input_type -> dynamicfilter.QueryStatusRequest
	9,  // 13: dynamicfilter.DynamicFilterService.CollectValues:input_type -> dynamicfilter.CollectValueRequest
	13, // 14: dynamicfilter.DynamicFilterService.GetFilter:input_type -> dynamicfilter.GetFilterRequest
	15, // 15: dynamicfilter.DynamicFilterService.WaitForFilter:input_type -> dynamicfilter.WaitForFilterRequest
	20, // 16: dynamicfilter.DynamicFilterService.RegisterSegment:input_type -> dynamicfilter.RegisterSegmentRequest
	11, // 17: dynamicfilter.DynamicFilterService.SignalSourceComplete:input_type -> dynamicfilter.SignalSourceCompleteRequest
	3,  // 18: dynamicfilter.DynamicFilterService.StartQuery:output_type -> dynamicfilter.StartQueryResponse
	5,  // 19: dynamicfilter.DynamicFilterService.StopQuery:output_type -> dynamicfilter.StopQueryResponse
	7,  // 20: dynamicfilter.DynamicFilterService.QueryStatus:output_type -> dynamicfilter.QueryStatusResponse
	10, // 21: dynamicfilter.DynamicFilterService.CollectValues:output_type -> dynamicfilter.CollectValueResponse
	14, // 22: dynamicfilter.DynamicFilterService.GetFilter:output_type -> dynamicfilter.GetFilterResponse
	16, // 23: dynamicfilter.DynamicFilterService.WaitForFilter:output_type -> dynamicfilter.WaitForFilterResponse
	21, // 24: dynamicfilter.DynamicFilterService.RegisterSegment:output_type -> dynamicfilter.RegisterSegmentResponse
	12, // 25: dynamicfilter.DynamicFilterService.SignalSourceComplete:output_type -> dynamicfilter.SignalSourceCompleteResponse
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_dynamic_filter_proto_init() }
func file_dynamic_filter_proto_init() {
	if File_dynamic_filter_proto != nil {
		return
	}
	file_dynamic_filter_proto_msgTypes[17].OneofWrappers = []any{
		(*Literal_BoolValue)(nil),
		(*Literal_Int32Value)(nil),
		(*Literal_Int64Value)(nil),
		(*Literal_Float32Value)(nil),
		(*Literal_Float64Value)(nil),
		(*Literal_StringValue)(nil),
		(*Literal_BytesValue)(nil),
		(*Literal_DateValue)(nil),
		(*Literal_TimeValue)(nil),
		(*Literal_TimestampValue)(nil),
		(*Literal_DecimalValue)(nil),
		(*Literal_UuidValue)(nil),
		(*Literal_FixedValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dynamic_filter_proto_rawDesc), len(file_dynamic_filter_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dynamic_filter_proto_goTypes,
		DependencyIndexes: file_dynamic_filter_proto_depIdxs,
		EnumInfos:         file_dynamic_filter_proto_enumTypes,
		MessageInfos:      file_dynamic_filter_proto_msgTypes,
	}.Build()
	File_dynamic_filter_proto = out.File
	file_dynamic_filter_proto_goTypes = nil
	file_dynamic_filter_proto_depIdxs = nil
}
