// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.32.0
// source: dynamic_filter.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DynamicFilterService_StartQuery_FullMethodName           = "/dynamicfilter.DynamicFilterService/StartQuery"
	DynamicFilterService_StopQuery_FullMethodName            = "/dynamicfilter.DynamicFilterService/StopQuery"
	DynamicFilterService_QueryStatus_FullMethodName          = "/dynamicfilter.DynamicFilterService/QueryStatus"
	DynamicFilterService_CollectValues_FullMethodName        = "/dynamicfilter.DynamicFilterService/CollectValues"
	DynamicFilterService_GetFilter_FullMethodName            = "/dynamicfilter.DynamicFilterService/GetFilter"
	DynamicFilterService_WaitForFilter_FullMethodName        = "/dynamicfilter.DynamicFilterService/WaitForFilter"
	DynamicFilterService_RegisterSegment_FullMethodName      = "/dynamicfilter.DynamicFilterService/RegisterSegment"
	DynamicFilterService_SignalSourceComplete_FullMethodName = "/dynamicfilter.DynamicFilterService/SignalSourceComplete"
)

// DynamicFilterServiceClient is the client API for DynamicFilterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DynamicFilterService предоставляет RPC методы для управления динамическими фильтрами
// в распределённой среде Greenplum FDW
type DynamicFilterServiceClient interface {
	// Управление сессиями запросов
	StartQuery(ctx context.Context, in *StartQueryRequest, opts ...grpc.CallOption) (*StartQueryResponse, error)
	StopQuery(ctx context.Context, in *StopQueryRequest, opts ...grpc.CallOption) (*StopQueryResponse, error)
	QueryStatus(ctx context.Context, in *QueryStatusRequest, opts ...grpc.CallOption) (*QueryStatusResponse, error)
	// Сбор значений от source таблиц (streaming для эффективности)
	CollectValues(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CollectValueRequest, CollectValueResponse], error)
	// Получение фильтров для target таблиц
	GetFilter(ctx context.Context, in *GetFilterRequest, opts ...grpc.CallOption) (*GetFilterResponse, error)
	WaitForFilter(ctx context.Context, in *WaitForFilterRequest, opts ...grpc.CallOption) (*WaitForFilterResponse, error)
	// Синхронизация сегментов
	RegisterSegment(ctx context.Context, in *RegisterSegmentRequest, opts ...grpc.CallOption) (*RegisterSegmentResponse, error)
	SignalSourceComplete(ctx context.Context, in *SignalSourceCompleteRequest, opts ...grpc.CallOption) (*SignalSourceCompleteResponse, error)
}

type dynamicFilterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDynamicFilterServiceClient(cc grpc.ClientConnInterface) DynamicFilterServiceClient {
	return &dynamicFilterServiceClient{cc}
}

func (c *dynamicFilterServiceClient) StartQuery(ctx context.Context, in *StartQueryRequest, opts ...grpc.CallOption) (*StartQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartQueryResponse)
	err := c.cc.Invoke(ctx, DynamicFilterService_StartQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicFilterServiceClient) StopQuery(ctx context.Context, in *StopQueryRequest, opts ...grpc.CallOption) (*StopQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopQueryResponse)
	err := c.cc.Invoke(ctx, DynamicFilterService_StopQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicFilterServiceClient) QueryStatus(ctx context.Context, in *QueryStatusRequest, opts ...grpc.CallOption) (*QueryStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryStatusResponse)
	err := c.cc.Invoke(ctx, DynamicFilterService_QueryStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicFilterServiceClient) CollectValues(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[CollectValueRequest, CollectValueResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DynamicFilterService_ServiceDesc.Streams[0], DynamicFilterService_CollectValues_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CollectValueRequest, CollectValueResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DynamicFilterService_CollectValuesClient = grpc.ClientStreamingClient[CollectValueRequest, CollectValueResponse]

func (c *dynamicFilterServiceClient) GetFilter(ctx context.Context, in *GetFilterRequest, opts ...grpc.CallOption) (*GetFilterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFilterResponse)
	err := c.cc.Invoke(ctx, DynamicFilterService_GetFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicFilterServiceClient) WaitForFilter(ctx context.Context, in *WaitForFilterRequest, opts ...grpc.CallOption) (*WaitForFilterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WaitForFilterResponse)
	err := c.cc.Invoke(ctx, DynamicFilterService_WaitForFilter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicFilterServiceClient) RegisterSegment(ctx context.Context, in *RegisterSegmentRequest, opts ...grpc.CallOption) (*RegisterSegmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterSegmentResponse)
	err := c.cc.Invoke(ctx, DynamicFilterService_RegisterSegment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dynamicFilterServiceClient) SignalSourceComplete(ctx context.Context, in *SignalSourceCompleteRequest, opts ...grpc.CallOption) (*SignalSourceCompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignalSourceCompleteResponse)
	err := c.cc.Invoke(ctx, DynamicFilterService_SignalSourceComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DynamicFilterServiceServer is the server API for DynamicFilterService service.
// All implementations must embed UnimplementedDynamicFilterServiceServer
// for forward compatibility.
//
// DynamicFilterService предоставляет RPC методы для управления динамическими фильтрами
// в распределённой среде Greenplum FDW
type DynamicFilterServiceServer interface {
	// Управление сессиями запросов
	StartQuery(context.Context, *StartQueryRequest) (*StartQueryResponse, error)
	StopQuery(context.Context, *StopQueryRequest) (*StopQueryResponse, error)
	QueryStatus(context.Context, *QueryStatusRequest) (*QueryStatusResponse, error)
	// Сбор значений от source таблиц (streaming для эффективности)
	CollectValues(grpc.ClientStreamingServer[CollectValueRequest, CollectValueResponse]) error
	// Получение фильтров для target таблиц
	GetFilter(context.Context, *GetFilterRequest) (*GetFilterResponse, error)
	WaitForFilter(context.Context, *WaitForFilterRequest) (*WaitForFilterResponse, error)
	// Синхронизация сегментов
	RegisterSegment(context.Context, *RegisterSegmentRequest) (*RegisterSegmentResponse, error)
	SignalSourceComplete(context.Context, *SignalSourceCompleteRequest) (*SignalSourceCompleteResponse, error)
	mustEmbedUnimplementedDynamicFilterServiceServer()
}

// UnimplementedDynamicFilterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDynamicFilterServiceServer struct{}

func (UnimplementedDynamicFilterServiceServer) StartQuery(context.Context, *StartQueryRequest) (*StartQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartQuery not implemented")
}
func (UnimplementedDynamicFilterServiceServer) StopQuery(context.Context, *StopQueryRequest) (*StopQueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopQuery not implemented")
}
func (UnimplementedDynamicFilterServiceServer) QueryStatus(context.Context, *QueryStatusRequest) (*QueryStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryStatus not implemented")
}
func (UnimplementedDynamicFilterServiceServer) CollectValues(grpc.ClientStreamingServer[CollectValueRequest, CollectValueResponse]) error {
	return status.Error(codes.Unimplemented, "method CollectValues not implemented")
}
func (UnimplementedDynamicFilterServiceServer) GetFilter(context.Context, *GetFilterRequest) (*GetFilterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFilter not implemented")
}
func (UnimplementedDynamicFilterServiceServer) WaitForFilter(context.Context, *WaitForFilterRequest) (*WaitForFilterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WaitForFilter not implemented")
}
func (UnimplementedDynamicFilterServiceServer) RegisterSegment(context.Context, *RegisterSegmentRequest) (*RegisterSegmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterSegment not implemented")
}
func (UnimplementedDynamicFilterServiceServer) SignalSourceComplete(context.Context, *SignalSourceCompleteRequest) (*SignalSourceCompleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignalSourceComplete not implemented")
}
func (UnimplementedDynamicFilterServiceServer) mustEmbedUnimplementedDynamicFilterServiceServer() {}
func (UnimplementedDynamicFilterServiceServer) testEmbeddedByValue()                              {}

// UnsafeDynamicFilterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DynamicFilterServiceServer will
// result in compilation errors.
type UnsafeDynamicFilterServiceServer interface {
	mustEmbedUnimplementedDynamicFilterServiceServer()
}

func RegisterDynamicFilterServiceServer(s grpc.ServiceRegistrar, srv DynamicFilterServiceServer) {
	// If the following call panics, it indicates UnimplementedDynamicFilterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DynamicFilterService_ServiceDesc, srv)
}

func _DynamicFilterService_StartQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicFilterServiceServer).StartQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicFilterService_StartQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicFilterServiceServer).StartQuery(ctx, req.(*StartQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicFilterService_StopQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicFilterServiceServer).StopQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicFilterService_StopQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicFilterServiceServer).StopQuery(ctx, req.(*StopQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicFilterService_QueryStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicFilterServiceServer).QueryStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicFilterService_QueryStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicFilterServiceServer).QueryStatus(ctx, req.(*QueryStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicFilterService_CollectValues_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DynamicFilterServiceServer).CollectValues(&grpc.GenericServerStream[CollectValueRequest, CollectValueResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DynamicFilterService_CollectValuesServer = grpc.ClientStreamingServer[CollectValueRequest, CollectValueResponse]

func _DynamicFilterService_GetFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicFilterServiceServer).GetFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicFilterService_GetFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicFilterServiceServer).GetFilter(ctx, req.(*GetFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicFilterService_WaitForFilter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaitForFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicFilterServiceServer).WaitForFilter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicFilterService_WaitForFilter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicFilterServiceServer).WaitForFilter(ctx, req.(*WaitForFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicFilterService_RegisterSegment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSegmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicFilterServiceServer).RegisterSegment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicFilterService_RegisterSegment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicFilterServiceServer).RegisterSegment(ctx, req.(*RegisterSegmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DynamicFilterService_SignalSourceComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignalSourceCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DynamicFilterServiceServer).SignalSourceComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DynamicFilterService_SignalSourceComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DynamicFilterServiceServer).SignalSourceComplete(ctx, req.(*SignalSourceCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DynamicFilterService_ServiceDesc is the grpc.ServiceDesc for DynamicFilterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DynamicFilterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dynamicfilter.DynamicFilterService",
	HandlerType: (*DynamicFilterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartQuery",
			Handler:    _DynamicFilterService_StartQuery_Handler,
		},
		{
			MethodName: "StopQuery",
			Handler:    _DynamicFilterService_StopQuery_Handler,
		},
		{
			MethodName: "QueryStatus",
			Handler:    _DynamicFilterService_QueryStatus_Handler,
		},
		{
			MethodName: "GetFilter",
			Handler:    _DynamicFilterService_GetFilter_Handler,
		},
		{
			MethodName: "WaitForFilter",
			Handler:    _DynamicFilterService_WaitForFilter_Handler,
		},
		{
			MethodName: "RegisterSegment",
			Handler:    _DynamicFilterService_RegisterSegment_Handler,
		},
		{
			MethodName: "SignalSourceComplete",
			Handler:    _DynamicFilterService_SignalSourceComplete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CollectValues",
			Handler:       _DynamicFilterService_CollectValues_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "dynamic_filter.proto",
}
